
version: "3"
services:
  backend:
    build: backend
    environment:
      MONGODB_CONNECTION_STRING: "mongodb://mongodb/wtm"
      PORT: "3001"
    ports:
      - 3001:3001
  frontend:
    image: registry.heroku.com/jscc19-yasemin-frontend
    build: frontend
    environment:
      VUE_APP_API_URL: "http://localhost:3001"
      PORT: "8080"
    ports:
      - 8080:8080
  mongodb:
    image: mongo:4.4
    ports:
      - 27017:27017